config/routes.rb
Rssfeedreader::Application.routes.draw do
  resources :rssfeeds

  devise_for :users

  root :to => 'home#index'
  match '/feedlist' => 'rssfeeds#index'
  match '/withfeedjira' => 'rssfeeds#withfeedjira'
  

end

app/models/rssfeed.rb
class Rssfeed < ActiveRecord::Base
  attr_accessible :feedurl
  belongs_to :user, :class_name => "User", :foreign_key => "user_id"

  validates_presence_of :feedurl
  validates_uniqueness_of :feedurl, :message => "is already added."
  validate :validurl

  per_page = 1

	def validurl
		begin
			open(self.feedurl) do |rss|
			  feed = RSS::Parser.parse(rss)
			  @title = feed.channel.title
			  if @title.blank?
			  	errors.add(:feedurl, "is not valid.")
			  else
			  	true
			  end
			end
		rescue => error
			errors.add(:feedurl, "is not valid.")
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name
  # attr_accessible :title, :body

  has_many :rssfeeds, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/rssfeeds_controller.rb
class RssfeedsController < ApplicationController
	before_filter :authenticate_user!
  # GET /rssfeeds
  # GET /rssfeeds.json
  def index
    @feedsurls = current_user.rssfeeds
    @rssfeeds = @feedsurls.paginate :page => params[:page], :per_page => 1, :order => "created_at DESC"
    
    @rssfeed = Rssfeed.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rssfeeds }
    end
  end

  # GET /rssfeeds/1
  # GET /rssfeeds/1.json
  def show
    @rssfeed = Rssfeed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rssfeed }
    end
  end

  # GET /rssfeeds/new
  # GET /rssfeeds/new.json
  def new
    @rssfeed = Rssfeed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rssfeed }
    end
  end

  # GET /rssfeeds/1/edit
  def edit
    @rssfeed = Rssfeed.find(params[:id])
  end

  # POST /rssfeeds
  # POST /rssfeeds.json
  def create
    @rssfeed = Rssfeed.new(params[:rssfeed])
    @rssfeed.user_id = current_user.id
    respond_to do |format|
      if @rssfeed.save
        format.html { redirect_to @rssfeed, notice: 'Rssfeed was successfully created.' }
        format.json { render json: @rssfeed, status: :created, location: @rssfeed }
        format.js{}
      else
        format.html { render action: "new" }
        format.json { render json: @rssfeed.errors, status: :unprocessable_entity }
        format.js{}
      end
    end
  end

  # PUT /rssfeeds/1
  # PUT /rssfeeds/1.json
  def update
    @rssfeed = Rssfeed.find(params[:id])

    respond_to do |format|
      if @rssfeed.update_attributes(params[:rssfeed])
        format.html { redirect_to @rssfeed, notice: 'Rssfeed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rssfeed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rssfeeds/1
  # DELETE /rssfeeds/1.json
  def destroy
    @rssfeed = Rssfeed.find(params[:id])
    @rssfeed.destroy

    respond_to do |format|
      format.html { redirect_to rssfeeds_url, notice: 'Rssfeed was successfully deleted.'  }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rssfeeds_helper.rb
module RssfeedsHelper
	require 'rss'
	require 'open-uri'

	def rssitem_html_view(item)

		@subitems = []
		open(item.feedurl) do |rss|
		  feed = RSS::Parser.parse(rss)
		  @title = feed.channel.title

		  feed.items.each do |item|
		  	@subitems << item
		  end
		end

	end
end

app/views/home/index.html.erb
<div class="starter-template">
	<h1>RSS feed reader basic application</h1>
	<p class="lead">Save your URL to your profile<br> We will display you all the related feeds.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Personalize your RSS feeds</title>
    <%= stylesheet_link_tag  "application", "bootstrap.min", "starter-template", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">RSS Feed Reader</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == "home" ? 'active' : '' %>"><a href="/">Home</a></li>
            <% if current_user %>
            	<li class="<%= params[:controller] == "rssfeeds" ? 'active' : '' %>"><a href="/rssfeeds">Feeds</a></li>
            	<li class="<%= params[:controller] == "devise/sessions" ? 'active' : '' %>"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            <% else %>
            	<li class="<%= params[:controller] == "devise/sessions" ? 'active' : '' %>"><a href="/users/sign_in">Sign In</a></li>
            	<li class="<%= params[:controller] == "devise/registrations" ? 'active' : '' %>"><a href="/users/sign_up">Sign Up</a></li>
            <% end %>
          </ul>
          <% if current_user %>
            <div class="pull-right text-white username-info">Welcome <%= current_user.first_name %> <%= current_user.last_name %></div>
          <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
    	<div class="flash-content">
			<% if flash[:alert] %>
				<div class="alert alert-danger"><%= flash[:alert] %></div>
			<% end %>
			<% if flash[:notice] %>
				<div class="alert alert-success"><%= flash[:notice] %></div>
			<% end %>
		</div>
		<div class="main-display-content">
      		<%= yield %>
      	</div>
    </div>

  </body>
</html>

app/views/rssfeeds/_feed_list.html.erb
<h3><%= title %></h3>
<hr>
<% items.each do |item| %>
	<p><%= item.title %></p>
	<% if item.class.name == "Feedjira::Parser::RSSEntry" %>
		<p><a href="<%= item.url %>"><%= item.url %></a></p>
	<% else %>
		<p><a href="<%= item.link %>"><%= item.link %></a></p>
	<% end %>
<% end %>

app/views/rssfeeds/_form.html.erb
<%= form_for(@rssfeed) do |f| %>
  <% if @rssfeed.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @rssfeed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :feedurl %><br />
    <%= f.text_field :feedurl, :size => 80, :class => "form-control" %>
  </div>
  <div class="actions">
    <button type="submit" class="btn btn-primary" value="Create Rssfeed" name="commit">Submit</button>
  </div>
<% end %>

app/views/rssfeeds/_index.html.erb
<% @rssfeeds.each do |rssfeed| %>
	<% rssitem_html_view(rssfeed) %>
	<h3><%= @title %></h3>
	<hr>
	<%#= @subitems.first.inspect %>
	<% @subitems.each do |item| %>
		<blockquote>
			<h3><%= item.title.html_safe %></h3>
	  		<% if item.class.name == "Feedjira::Parser::RSSEntry" %>
				<p><a href="<%= item.url %>"><%= item.url %></a></p>
			<% else %>
				<p><a href="<%= item.link %>"><%= item.link %></a></p>
			<% end %>
		</blockquote>
		
		<p><%= item.description.html_safe unless item.description.blank? %></p>
		<br/>
	<% end %>

<% end %>

<%= will_paginate @rssfeeds, renderer: BootstrapPagination::Rails %>

app/views/rssfeeds/_list.html.erb
<ul>
	<% @feedsurls.each do |rssfeed| %>
  		<li><a href="/rssfeeds/<%= rssfeed.id %>"><%= rssfeed.feedurl %></a></li>
  	<% end %>
</ul>

app/views/rssfeeds/create.js.erb
<% unless @rssfeed.errors.blank? %>
  <% @rssfeed.errors.full_messages.each do |msg| %>
    $("#error_explanation").append("<%= msg %>")
  <% end %>
<% else %>
	window.location.reload();
<% end %>

app/views/rssfeeds/edit.html.erb
<h1>Editing rssfeed</h1>

<%= render 'form' %>

<%= link_to 'Show', @rssfeed %> |
<%= link_to 'Back', rssfeeds_path %>

app/views/rssfeeds/index.html.erb
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><a href="#allcontents" role="tab" data-toggle="tab">All Contents</a></li>
  <li><a href="#feeds" role="tab" data-toggle="tab">Feeds</a></li>
  <li><a href="#newfeed" role="tab" data-toggle="tab">Add New URL</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content tabbody">
  <div class="tab-pane active" id="allcontents">
    <%= render :partial => "rssfeeds/index" %>
  </div>
  <div class="tab-pane" id="feeds">
    <%= render :partial => "rssfeeds/list" %>
  </div>
  <div class="tab-pane" id="newfeed">
    <%= render :partial => 'rssfeeds/form' %>
  </div>
</div>

app/views/rssfeeds/index.js.erb
<% if defined?(@errors) %>
	$("#feed_container").html('<%= @errors %>');
<% else %>
	$("#feed_container").html('<%= escape_javascript(render :partial=>"rssfeeds/feed_list", :locals => {:title => @title, :items => @rssitems}) %>');
<% end %>

app/views/rssfeeds/new.html.erb
<h1>New rssfeed</h1>

<%= render 'form' %>

<%= link_to 'Back', rssfeeds_path %>

app/views/rssfeeds/show.html.erb
<p>
<h1><%= @rssfeed.feedurl %><h1>

<% rssitem_html_view(@rssfeed) %>
<h3><%= @title %></h3>
<hr>
<% @subitems.each do |item| %>
	<p><%= item.title %></p>
	<% if item.class.name == "Feedjira::Parser::RSSEntry" %>
		<p><a href="<%= item.url %>"><%= item.url %></a></p>
	<% else %>
		<p><a href="<%= item.link %>"><%= item.link %></a></p>
	<% end %>
<% end %>
<hr>
<%= link_to 'Edit', edit_rssfeed_path(@rssfeed), :class => "btn btn-default active" %> |
<%= link_to 'Back', rssfeeds_path, :class => "btn btn-default active" %> |
<%= link_to 'Destroy', rssfeed_path(@rssfeed, :authenticity_token => form_authenticity_token), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default active" %>
</p>

app/views/rssfeeds/withfeedjira.js.erb
<% if defined?(@errors) %>
	$("#feed_container").html('<%= @errors %>');
<% else %>
	$("#feed_container").html('<%= escape_javascript(render :partial=>"rssfeeds/feed_list", :locals => {:title => @title, :items => @rssitems}) %>');
<% end %>